changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 핵심 수정 사항 🛠
      labels:
        - '*'
    - title: 신규 기능 추가 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
