changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - zxcv9203
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
        - CI/CD
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
